[2023-09-21T13:51:13.641+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cleaning_dag.wait_for_csv manual__2023-09-21T13:50:07.961935+00:00 [queued]>
[2023-09-21T13:51:13.661+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cleaning_dag.wait_for_csv manual__2023-09-21T13:50:07.961935+00:00 [queued]>
[2023-09-21T13:51:13.662+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T13:51:13.679+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonSensor): wait_for_csv> on 2023-09-21 13:50:07.961935+00:00
[2023-09-21T13:51:13.699+0000] {standard_task_runner.py:57} INFO - Started process 16130 to run task
[2023-09-21T13:51:13.707+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'cleaning_dag', 'wait_for_csv', 'manual__2023-09-21T13:50:07.961935+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/cleaning_dag.py', '--cfg-path', '/tmp/tmpg3juq0gh']
[2023-09-21T13:51:13.715+0000] {standard_task_runner.py:85} INFO - Job 176: Subtask wait_for_csv
[2023-09-21T13:51:13.820+0000] {task_command.py:415} INFO - Running <TaskInstance: cleaning_dag.wait_for_csv manual__2023-09-21T13:50:07.961935+00:00 [running]> on host c14470e00ccc
[2023-09-21T13:51:14.079+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felicien' AIRFLOW_CTX_DAG_ID='cleaning_dag' AIRFLOW_CTX_TASK_ID='wait_for_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T13:50:07.961935+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-21T13:50:07.961935+00:00'
[2023-09-21T13:51:14.083+0000] {python.py:72} INFO - Poking callable: <function check_csv_exists at 0xffff87ac4e50>
[2023-09-21T13:52:14.097+0000] {python.py:72} INFO - Poking callable: <function check_csv_exists at 0xffff87ac4e50>
[2023-09-21T13:53:14.122+0000] {python.py:72} INFO - Poking callable: <function check_csv_exists at 0xffff87ac4e50>
[2023-09-21T13:54:14.176+0000] {python.py:72} INFO - Poking callable: <function check_csv_exists at 0xffff87ac4e50>
[2023-09-21T13:55:14.259+0000] {python.py:72} INFO - Poking callable: <function check_csv_exists at 0xffff87ac4e50>
[2023-09-21T13:56:14.340+0000] {python.py:72} INFO - Poking callable: <function check_csv_exists at 0xffff87ac4e50>
[2023-09-21T13:56:30.453+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-09-21T13:56:30.475+0000] {process_utils.py:131} INFO - Sending 15 to group 16130. PIDs of all processes in the group: [16130]
[2023-09-21T13:56:30.480+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 16130
[2023-09-21T13:56:30.500+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-09-21T13:56:30.642+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=16130, status='terminated', exitcode=0, started='13:51:13') (16130) terminated with exit code 0
